name: starter
description: A basic Flutter project to use as a starting place for other applications
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  package_info_plus: ^1.0.3
  shared_preferences: ^2.0.6
  flutter_secure_storage: ^4.2.0
  scoped_model: ^2.0.0-nullsafety.0

dev_dependencies:
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.0

# Run `flutter pub run flutter_native_splash:create` to generate native splash screen code.
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png

  #color_dark: "#000000"
  #image_dark: assets/images/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
